### ISSUE TITLE
Can't delete artifacts in mertics

### ISSUE THREAD

**Issue by Slach** [moira-alert/worker#17]
i have Moira-worker installed over https://github.com/moira-alert/worker/releases/download/v1.1.14/moira_worker-1.1.14.tar.gz

i try delete artifacts described in https://github.com/moira-alert/worker/issues/16
and i have 500 error 

<pre>
2016-05-12 13:13:51+0000 [_GenericHTTPChannelProtocol,13,127.0.0.1] Unhandled Error
        Traceback (most recent call last):
          File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1274, in unwindGenerator
            return _inlineCallbacks(None, gen, Deferred())
          File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
            result = g.send(result)
          File "/usr/local/lib/python2.7/dist-packages/moira/api/request.py", line 89, in wrapper
            yield f(resource, request)
          File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1274, in unwindGenerator
            return _inlineCallbacks(None, gen, Deferred())
        --- <exception caught here> ---
          File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
            result = g.send(result)
          File "/usr/local/lib/python2.7/dist-packages/moira/api/resources/metric.py", line 36, in render_DELETE
            metric = request.args.get('name')[0]
        exceptions.TypeError: 'NoneType' object has no attribute '__getitem__'

2016-05-12 13:13:51+0000 [-] - 0.001 "DELETE /api/trigger/668d5aa4-48ef-4a56-a7e5-2920daa4b4c5/metrics?args HTTP/1.0" 500 -
</pre>

**Comment by Slach** [comment]
sorry it's bug in my nginx config
?args
need replace to ?$args

**Comment by gmlexx** [comment]
Ok, just curious, what is the point in such nginx config?

**Comment by Slach** [comment]
My current nginx config
<pre>
#MOIRA
upstream moira_backend {
    server 127.0.0.1:8081;
}
server {
    listen 80;
    server_name local.moira.coffee-monitor;

    auth_basic "private area";
    auth_basic_user_file /etc/nginx/conf.d/.htpasswd.secret;

    location / {
        root /var/www/moira;
        index index.html;
    }

    location ~ ^/api/(.*)$ {
        # bug was here
        proxy_pass http://moira_backend/api/$1?$args;
        proxy_set_header Host $http_host;
        proxy_set_header X-Auth-User $remote_user;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
</pre>

**Comment by gmlexx** [comment]
Nginx best practices guide to avoid use regexp in locations.

So you can just use location /api/

And proxy_pass http://moira_backend/ <http://moira_backend/api/$1?$args>
