### ISSUE TITLE
Moira-checker ignored args

### ISSUE THREAD

**Issue by AlexAkulov** [moira-alert/worker#18]
Moira-checker ignored args
```
[akulov@vm-edi-graph3 ~]$ moira-checker -t a6b3a011-5203-4598-98fa-e4d6d2a8b797 -l /home/akulov/log/
Traceback (most recent call last):
  File "/usr/bin/moira-checker", line 9, in <module>
    load_entry_point('moira-worker===master', 'console_scripts', 'moira-checker')()
  File "/usr/lib/python2.7/site-packages/moira/checker/server.py", line 50, in run
    logs.checker_master()
  File "/usr/lib/python2.7/site-packages/moira/logs.py", line 33, in checker_master
    log.startLogging(FileLogObserver(daily("checker.log")))
  File "/usr/lib/python2.7/site-packages/moira/logs.py", line 47, in daily
    return ZeroPaddingDailyLogFile(name, path)
  File "/usr/lib/python2.7/site-packages/Twisted-15.2.1-py2.7-linux-x86_64.egg/twisted/python/logfile.py", line 40, in __init__
    self._openFile()
  File "/usr/lib/python2.7/site-packages/Twisted-15.2.1-py2.7-linux-x86_64.egg/twisted/python/logfile.py", line 238, in _openFile
    BaseLogFile._openFile(self)
  File "/usr/lib/python2.7/site-packages/Twisted-15.2.1-py2.7-linux-x86_64.egg/twisted/python/logfile.py", line 64, in _openFile
    self._file = file(self.path, "r+", 1)
IOError: [Errno 13] Permission denied: '/var/log/moira/worker/checker.log'
```

**Comment by le9i0nx** [comment]
file exists?
/etc/moira/config.yml
this variable has a value?
 cfg['worker']['log_dir']

**Comment by gmlexx** [comment]
As you can see and tried fix, the settings from config file override argument settings.
That is not expected.
Commented your #26. One last step to fix remained.

**Comment by le9i0nx** [comment]
I corrected your patch.
I think it is now ready.
