### ISSUE TITLE
Targets with {} don't work

### ISSUE THREAD

**Issue by AlexAkulov** [moira-alert/worker#28]
I can't added trigger with this target `aliasByNode(KE.Databases.{Mirroring,AG}.*.IsSynchronized,3)`

```
2016-06-07 11:14:23+0300 [BaseRedisProtocol,client] Unhandled Error
        Traceback (most recent call last):
          File "/usr/lib/python2.7/site-packages/Twisted-15.2.1-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 1184, in gotResult
            _inlineCallbacks(r, g, deferred)
          File "/usr/lib/python2.7/site-packages/Twisted-15.2.1-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 1128, in _inlineCallbacks
            result = g.send(result)
          File "/usr/lib/python2.7/site-packages/moira_worker-1.2.3.dev1_gb3445cb-py2.7.egg/moira/graphite/evaluator.py", line 103, in evaluateTokens
            defer.returnValue((yield func(requestContext, *args, **kwargs)))
          File "/usr/lib/python2.7/site-packages/Twisted-15.2.1-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 1274, in unwindGenerator
            return _inlineCallbacks(None, gen, Deferred())
        --- <exception caught here> ---
          File "/usr/lib/python2.7/site-packages/Twisted-15.2.1-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 1128, in _inlineCallbacks
            result = g.send(result)
          File "/usr/lib/python2.7/site-packages/moira_worker-1.2.3.dev1_gb3445cb-py2.7.egg/moira/graphite/functions.py", line 1628, in aliasByNode
            series.name = '.'.join(metric_pieces[n] for n in nodes)
          File "/usr/lib/python2.7/site-packages/moira_worker-1.2.3.dev1_gb3445cb-py2.7.egg/moira/graphite/functions.py", line 1628, in <genexpr>
            series.name = '.'.join(metric_pieces[n] for n in nodes)
        exceptions.IndexError: list index out of range
```
```
pip list | grep moi
moira-worker (1.2.3.dev1-gb3445cb)
```

**Comment by gmlexx** [comment]
This is graphite bug, but you don't see it on graphite if target pattern matched any metric.
