### ISSUE TITLE
Web application breaks if tag containing only numbers is created

### ISSUE THREAD

**Issue by bersegosx** [moira-alert/worker#39]
Chromium Version 52.0.2743.116, console:

```
angular.js:12416 TypeError: b.value.toLowerCase is not a function
    at http://127.0.0.1:8080/app-c04c88e6cf11fa8e8fce.js:750:69
    at TagList.sort (native)
    at http://127.0.0.1:8080/app-c04c88e6cf11fa8e8fce.js:749:32
    at processQueue (http://127.0.0.1:8080/common-c04c88e6cf11fa8e8fce.js:14760:29)
    at http://127.0.0.1:8080/common-c04c88e6cf11fa8e8fce.js:14776:28
    at Scope.$eval (http://127.0.0.1:8080/common-c04c88e6cf11fa8e8fce.js:16042:29)
    at Scope.$digest (http://127.0.0.1:8080/common-c04c88e6cf11fa8e8fce.js:15853:32)
    at Scope.$apply (http://127.0.0.1:8080/common-c04c88e6cf11fa8e8fce.js:16150:25)
    at done (http://127.0.0.1:8080/common-c04c88e6cf11fa8e8fce.js:10637:48)
    at completeRequest (http://127.0.0.1:8080/common-c04c88e6cf11fa8e8fce.js:10809:8)
```

GET request on `/api/tag/`:

```json
{
    "list": [
        666,
        "qwe",
        "cat",
        "lop",
        "nata",
        "5555dsfg"
    ],
    "tags": {
        "5555dsfg": {},
        "666": {},
        "cat": {},
        "lop": {},
        "nata": {},
        "qwe": {}
    }
}

```
I use:

- anyjson==0.3.3
- txredisapi==1.4.3
- redis_version:3.2.3

**Comment by gmlexx** [comment]
Fixed in @7e6df61
